name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest  # образ
    steps:
      - uses: actions/checkout@v2 # github actions
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install Node.js
        env:
          NODE_VERSION: 14.17.0
        run: nvm install $NODE_VERSION
      - name: Install deps
        run: npm i
      - name: Lint source code with ESLint
        run: npm run lint
